# Generated by Django 3.0.4 on 2020-05-08 03:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20200508_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='recipient',
            new_name='recipient_fr',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='sender',
            new_name='sender_fr',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender_fr', 'recipient_fr')},
        ),
    ]
