# Generated by Django 3.0.4 on 2020-05-08 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_auto_20200508_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='recipient_fr',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='sender_fr',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'recipient')},
        ),
    ]
